format = """
[░▒▓](#5EFE26)\
[](#5EFE26)\
$os\
$username\
[](bg:#0abdc6 fg:#5EFE26)\
$directory\
[](fg:#0abdc6 bg:#133e7c)\
$git_branch\
$git_status\
[](bg:#133e7c fg:#133e7c)\
[ ](fg:#133e7c)\
"""

[username]
show_always = true
style_user = "bg:#5EFE26 fg:#f57800"
style_root = "bg:#5EFE26"
format = '[  $user ]($style)'
 
[directory]
style = "bg:#0abdc6 fg:#f57800"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[character]
success_symbol = "[➜](bold purple)"
error_symbol = "[✗](bold red)"

[git_branch]
symbol = ""
style = "bg:#133e7c fg:#f57800"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#133e7c fg:#f57800"
format = '[$all_status$ahead_behind ]($style)'