cursor #ebe1d4
cursor_text_color #d1c5b4

foreground            #ebe1d4
background            #241f17
selection_foreground  #3b2f15
selection_background  #d9c4a0
url_color             #ebc16c

# black
color8   #ebe1d4
color0   #4c4c4c

# red
color1   #ffb4ab
color9   #c49ea0

# green
color2   #ebc16c
color10  #9ec49f

# yellow
color3   #aca98a
color11  #c4c19e

# blue
/* color4  #8f8aac */
color4  #ebc16c
color12 #a39ec4

# magenta
color5   #ffb4ab
color13  #c49ec4

# cyan
color6   #ebc16c
color14  #9ec3c4

# white
color15   #e7e7e7
color7  #f0f0f0
