opacity = 1 # currently setting opacity in Hyprland config, not here


font_family      Iosevka Nerd Font Bold
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12

allow_remote_control yes


# BEGIN_KITTY_THEME
# Matugen
include current-theme.conf
# END_KITTY_THEME
