[Desktop Entry]
Type=X-GNOME-Metatheme
Name=peaceful_pond
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=peaceful_pond
GtkTheme=peaceful_pond
IconTheme=peaceful_pond
MetacityTheme=peaceful_pond
