format = '''
$directory$git_branch
$character'''

palette = 'colors'

[palettes.colors]
primary = '#c8bfff'
tertiary = '#ecb8ce'
subtle = '#c9c5d0'

[character]
success_symbol = '[🞈](tertiary bold)'
error_symbol = '[🞈](red bold)'

[directory]
format = '[$path ](primary)'

[git_branch]
format = '[on ](subtle)[$branch](tertiary)'
