format = '''
$directory$git_branch
$character'''

palette = 'colors'

[palettes.colors]
primary = '#b0d18b'
tertiary = '#a0cfcc'
subtle = '#c4c8ba'

[character]
success_symbol = '[🞈](tertiary bold)'
error_symbol = '[🞈](red bold)'

[directory]
format = '[$path ](primary)'

[git_branch]
format = '[on ](subtle)[$branch](tertiary)'
