format = '''
$directory$git_branch
$character'''

palette = 'colors'

[palettes.colors]
primary = '#adc6ff'
tertiary = '#debcdf'
subtle = '#c4c6d0'

[character]
success_symbol = '[🞈](tertiary bold)'
error_symbol = '[🞈](red bold)'

[directory]
format = '[$path ](primary)'

[git_branch]
format = '[on ](subtle)[$branch](tertiary)'
